apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-core-service-controller-manager
  namespace: gitops
spec:
  template:
    spec:
      containers:
      - env:
        - name: SELF_HEAL_INTERVAL
          value: "0" 
        name: manager
